import { supabase } from "../supabaseClient";
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";

import {
  ArrowRight,
  BrainCircuit,
  Eye,
  EyeOff,
  Lightbulb,
  LockKeyhole,
  Mail,
  Sparkles,
  UserRound,
  GraduationCap,
} from "lucide-react";

function Register() {
  const navigate = useNavigate();

  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const [name, setName] = useState("");
  const [institution, setInstitution] = useState("");
  const [education, setEducation] = useState("");
  const [yearOfStudy, setYearOfStudy] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const [loading, setLoading] = useState(false);

  const handleRegister = async (e) => {
    e.preventDefault();

    // Check passwords
    if (password !== confirmPassword) {
      alert("Passwords do not match.");
      return;
    }

    if (password.length < 6) {
      alert("Password must be at least 6 characters.");
      return;
    }

    setLoading(true);

    try {
      // ==========================================
      // 1. CREATE USER IN SUPABASE AUTH
      // ==========================================

      const { data: authData, error: authError } =
        await supabase.auth.signUp({
          email: email,
          password: password,
        });

      if (authError) {
        console.error("AUTH ERROR:", authError);
        alert(authError.message);
        setLoading(false);
        return;
      }

      if (!authData.user) {
        alert("Account could not be created.");
        setLoading(false);
        return;
      }

      // This is the UUID generated by Supabase Auth
      const authId = authData.user.id;

      console.log("SUPABASE AUTH USER:", authData.user);
      console.log("AUTH UUID:", authId);

      // ==========================================
      // 2. SAVE STUDENT INFORMATION
      // ==========================================

      const { data: profileData, error: profileError } =
        await supabase
          .from("students")
          .insert([
            {
              auth_id: authId,
              name: name,
              institution: institution,
              education: education,
              year_of_study: yearOfStudy,
              email: email,
            },
          ])
          .select()
          .single();

      if (profileError) {
        console.error("PROFILE ERROR:", profileError);

        alert(
          "Account was created, but student information could not be saved.\n\n" +
            profileError.message
        );

        setLoading(false);
        return;
      }

      console.log("STUDENT PROFILE CREATED:", profileData);

      // ==========================================
      // 3. SUCCESS
      // ==========================================

      alert("Account created successfully!");

      // Student should now choose career
      navigate("/login");

    } catch (error) {
      console.error("REGISTRATION ERROR:", error);
      alert("Something went wrong. Please try again.");
    }

    setLoading(false);
  };

  return (
    <div className="auth-page register-page">

      {/* LEFT SIDE */}
      <div className="auth-left">

        <Link to="/" className="auth-brand">
          <div className="brand-mark">
            <Sparkles size={18} />
          </div>

          <div>
            <span className="brand-name">CAREERPATH</span>
            <span className="brand-subtitle">AI</span>
          </div>
        </Link>

        <div className="auth-content">

          <div className="auth-kicker">
            <span />
            START YOUR JOURNEY
          </div>

          <h1>
            Build a future
            <br />
            that feels <span>right.</span>
          </h1>

          <p className="auth-description">
            Create your CareerPath AI profile and start discovering careers,
            skills, and learning paths designed around you.
          </p>

          <form
            className="login-form"
            onSubmit={handleRegister}
          >

            {/* NAME */}
            <div className="input-group">
              <label htmlFor="name">Full Name</label>

              <div className="input-wrapper">
                <UserRound size={18} />

                <input
                  id="name"
                  type="text"
                  placeholder="Enter your full name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                />
              </div>
            </div>

            {/* INSTITUTION */}
            <div className="input-group">
              <label htmlFor="institution">
                Institution / College
              </label>

              <div className="input-wrapper">
                <GraduationCap size={18} />

                <input
                  id="institution"
                  type="text"
                  placeholder="Enter your college or institution"
                  value={institution}
                  onChange={(e) =>
                    setInstitution(e.target.value)
                  }
                  required
                />
              </div>
            </div>

            {/* EDUCATION */}
            <div className="input-group">
              <label htmlFor="education">
                Education / Degree
              </label>

              <div className="input-wrapper">
                <GraduationCap size={18} />

                <input
                  id="education"
                  type="text"
                  placeholder="e.g. BCA, B.Tech, B.Sc"
                  value={education}
                  onChange={(e) =>
                    setEducation(e.target.value)
                  }
                  required
                />
              </div>
            </div>

            {/* YEAR OF STUDY */}
            <div className="input-group">
              <label htmlFor="yearOfStudy">
                Year of Study
              </label>

              <div className="input-wrapper">

                <input
                  id="yearOfStudy"
                  type="text"
                  placeholder="e.g. 3rd Year"
                  value={yearOfStudy}
                  onChange={(e) =>
                    setYearOfStudy(e.target.value)
                  }
                  required
                />

              </div>
            </div>

            {/* EMAIL */}
            <div className="input-group">
              <label htmlFor="register-email">
                Email Address
              </label>

              <div className="input-wrapper">
                <Mail size={18} />

                <input
                  id="register-email"
                  type="email"
                  placeholder="Enter your email"
                  value={email}
                  onChange={(e) =>
                    setEmail(e.target.value)
                  }
                  required
                />
              </div>
            </div>

            {/* PASSWORD */}
            <div className="input-group">
              <label htmlFor="register-password">
                Password
              </label>

              <div className="input-wrapper">
                <LockKeyhole size={18} />

                <input
                  id="register-password"
                  type={
                    showPassword
                      ? "text"
                      : "password"
                  }
                  placeholder="Create a password"
                  value={password}
                  onChange={(e) =>
                    setPassword(e.target.value)
                  }
                  required
                />

                <button
                  type="button"
                  className="password-toggle"
                  onClick={() =>
                    setShowPassword(!showPassword)
                  }
                >
                  {showPassword ? (
                    <EyeOff size={18} />
                  ) : (
                    <Eye size={18} />
                  )}
                </button>
              </div>
            </div>

            {/* CONFIRM PASSWORD */}
            <div className="input-group">
              <label htmlFor="confirm-password">
                Confirm Password
              </label>

              <div className="input-wrapper">
                <LockKeyhole size={18} />

                <input
                  id="confirm-password"
                  type={
                    showConfirmPassword
                      ? "text"
                      : "password"
                  }
                  placeholder="Confirm your password"
                  value={confirmPassword}
                  onChange={(e) =>
                    setConfirmPassword(e.target.value)
                  }
                  required
                />

                <button
                  type="button"
                  className="password-toggle"
                  onClick={() =>
                    setShowConfirmPassword(
                      !showConfirmPassword
                    )
                  }
                >
                  {showConfirmPassword ? (
                    <EyeOff size={18} />
                  ) : (
                    <Eye size={18} />
                  )}
                </button>
              </div>
            </div>

            {/* TERMS */}
            <label className="remember-me register-terms">
              <input
                type="checkbox"
                required
              />

              <span>
                I agree to the Terms & Privacy Policy
              </span>
            </label>

            {/* CREATE ACCOUNT */}
            <button
              type="submit"
              className="auth-button"
              disabled={loading}
            >
              {loading
                ? "Creating Account..."
                : "Create Account"}

              {!loading && (
                <ArrowRight size={17} />
              )}
            </button>
              
          </form>

          <p className="register-text">
            Already have an account?

            <Link to="/login">
              {" "}Log in
            </Link>
          </p>

        </div>
      </div>

      {/* RIGHT SIDE */}
      <div className="auth-right register-visual">

        <div className="idea-glow" />
        <div className="idea-orbit idea-orbit-one" />
        <div className="idea-orbit idea-orbit-two" />
        <div className="idea-orbit idea-orbit-three" />

        <div className="idea-visual">

          <div className="idea-rings ring-one" />
          <div className="idea-rings ring-two" />

          <div className="idea-symbol">
            <Lightbulb
              size={86}
              strokeWidth={1.1}
            />
          </div>

          <div className="idea-label">
            <Sparkles size={14} />
            <span>IMAGINE • LEARN • CREATE</span>
          </div>

        </div>

        <div className="idea-node idea-node-one">
          <BrainCircuit size={18} />
          <span>THINK</span>
        </div>

        <div className="idea-node idea-node-two">
          <Lightbulb size={18} />
          <span>IDEA</span>
        </div>

        <div className="idea-node idea-node-three">
          <Sparkles size={18} />
          <span>DISCOVER</span>
        </div>

        <div className="idea-node idea-node-four">
          <ArrowRight size={18} />
          <span>GROW</span>
        </div>

        <div className="thinking-caption">
          <span />

          <p>
            Every great career starts
            <br />
            with <strong>one good idea.</strong>
          </p>
        </div>

      </div>

    </div>
  );
}

export default Register;